<?xml version="1.0" encoding="utf-8"?><Database Name="HospitalManagement" Class="HospitalManagementDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=laptop-s013149l\sqlexpress;Initial Catalog=HospitalManagement;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="DAL.Properties.Settings" SettingsPropertyName="HospitalManagementConnectionString5" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Account" Member="Accounts">
    <Type Name="Account">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="username" Type="System.String" DbType="Char(50)" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="Char(255)" CanBeNull="true" />
      <Column Name="startDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="staffID" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="Char(100)" CanBeNull="true" />
      <Association Name="Staff_Account" Member="Staff" ThisKey="staffID" OtherKey="id" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SupplyHistory" Member="SupplyHistories">
    <Type Name="SupplyHistory">
      <Column Name="id" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="itemID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="roomID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="nurseID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="dosage" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="unit" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="PatientID" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="typeSupply" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="dateSupply" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Item_SupplyHistory" Member="Item" ThisKey="itemID" OtherKey="ID" Type="Item" IsForeignKey="true" />
      <Association Name="Patient_SupplyHistory" Member="Patient" ThisKey="PatientID" OtherKey="id" Type="Patient" IsForeignKey="true" />
      <Association Name="Room_SupplyHistory" Member="Room" ThisKey="roomID" OtherKey="id" Type="Room" IsForeignKey="true" />
      <Association Name="Staff_SupplyHistory" Member="Staff" ThisKey="nurseID" OtherKey="id" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Appointment" Member="Appointments">
    <Type Name="Appointment">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="startDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="status" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="doctorID" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="patientID" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="Patient_Appointment" Member="Patient" ThisKey="patientID" OtherKey="id" Type="Patient" IsForeignKey="true" />
      <Association Name="Staff_Appointment" Member="Staff" ThisKey="doctorID" OtherKey="id" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.DailyCare" Member="DailyCares">
    <Type Name="DailyCare">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="shift" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="bloodPressure" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="bodyTempearature" Type="System.Decimal" DbType="Decimal(4,1)" CanBeNull="true" />
      <Column Name="pulseRate" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="dateCare" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="patientID" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="roomID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="nurseID" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="Patient_DailyCare" Member="Patient" ThisKey="patientID" OtherKey="id" Type="Patient" IsForeignKey="true" />
      <Association Name="Room_DailyCare" Member="Room" ThisKey="roomID" OtherKey="id" Type="Room" IsForeignKey="true" />
      <Association Name="Staff_DailyCare" Member="Staff" ThisKey="nurseID" OtherKey="id" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Department" Member="Departments">
    <Type Name="Department">
      <Column Name="id" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="departmentName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Department_Staff" Member="Staffs" ThisKey="id" OtherKey="departmentID" Type="Staff" />
    </Type>
  </Table>
  <Table Name="dbo.DoctorPatient" Member="DoctorPatients">
    <Type Name="DoctorPatient">
      <Column Name="doctorID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="patientID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="startDate" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="endDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="role" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Patient_DoctorPatient" Member="Patient" ThisKey="patientID" OtherKey="id" Type="Patient" IsForeignKey="true" />
      <Association Name="Staff_DoctorPatient" Member="Staff" ThisKey="doctorID" OtherKey="id" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Inventory" Member="Inventories">
    <Type Name="Inventory">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ItemID" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LastUpdated" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Item_Inventory" Member="Item" ThisKey="ItemID" OtherKey="ID" Type="Item" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Items" Member="Items">
    <Type Name="Item">
      <Column Name="ID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="ItemType" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="Price" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Item_SupplyHistory" Member="SupplyHistories" ThisKey="ID" OtherKey="itemID" Type="SupplyHistory" />
      <Association Name="Item_Inventory" Member="Inventories" ThisKey="ID" OtherKey="ItemID" Type="Inventory" />
      <Association Name="Item_MedicalOrder" Member="MedicalOrders" ThisKey="ID" OtherKey="ItemID" Type="MedicalOrder" />
    </Type>
  </Table>
  <Table Name="dbo.LaboratoryTest" Member="LaboratoryTests">
    <Type Name="LaboratoryTest">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="MedicalOrderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="startDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="resultValue" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="resultUnit" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="result" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="MedicalOrder_LaboratoryTest" Member="MedicalOrder" ThisKey="MedicalOrderID" OtherKey="id" Type="MedicalOrder" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.LabTestType" Member="LabTestTypes">
    <Type Name="LabTestType">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="testTypeName" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Association Name="LabTestType_MedicalOrder" Member="MedicalOrders" ThisKey="id" OtherKey="TestTypeID" Type="MedicalOrder" />
    </Type>
  </Table>
  <Table Name="dbo.MedicalOrder" Member="MedicalOrders">
    <Type Name="MedicalOrder">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="PatientID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="DoctorID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="OrderType" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ItemID" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="TestTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HasLabTest" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Dosage" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Frequency" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Status" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="SignedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="MedicalOrder_LaboratoryTest" Member="LaboratoryTests" ThisKey="id" OtherKey="MedicalOrderID" Type="LaboratoryTest" />
      <Association Name="Item_MedicalOrder" Member="Item" ThisKey="ItemID" OtherKey="ID" Type="Item" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="LabTestType_MedicalOrder" Member="LabTestType" ThisKey="TestTypeID" OtherKey="id" Type="LabTestType" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="Patient_MedicalOrder" Member="Patient" ThisKey="PatientID" OtherKey="id" Type="Patient" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Staff_MedicalOrder" Member="Staff" ThisKey="DoctorID" OtherKey="id" Type="Staff" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.MedicalRecord" Member="MedicalRecords">
    <Type Name="MedicalRecord">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="patientID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="doctorID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="diagnosis" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="treatmentPlan" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="prescription" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="vitalSigns" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="createdDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="notes" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Association Name="Patient_MedicalRecord" Member="Patient" ThisKey="patientID" OtherKey="id" Type="Patient" IsForeignKey="true" />
      <Association Name="Staff_MedicalRecord" Member="Staff" ThisKey="doctorID" OtherKey="id" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Patient" Member="Patients">
    <Type Name="Patient">
      <Column Name="id" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="fullName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="dob" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="phoneNumber" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="TypePatient" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="citizenID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="InsuranceID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EmergencyContact" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EmergencyPhone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="createdDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="weight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="height" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Association Name="Patient_SupplyHistory" Member="SupplyHistories" ThisKey="id" OtherKey="PatientID" Type="SupplyHistory" />
      <Association Name="Patient_Appointment" Member="Appointments" ThisKey="id" OtherKey="patientID" Type="Appointment" />
      <Association Name="Patient_DailyCare" Member="DailyCares" ThisKey="id" OtherKey="patientID" Type="DailyCare" />
      <Association Name="Patient_DoctorPatient" Member="DoctorPatients" ThisKey="id" OtherKey="patientID" Type="DoctorPatient" />
      <Association Name="Patient_MedicalOrder" Member="MedicalOrders" ThisKey="id" OtherKey="PatientID" Type="MedicalOrder" />
      <Association Name="Patient_MedicalRecord" Member="MedicalRecords" ThisKey="id" OtherKey="patientID" Type="MedicalRecord" />
      <Association Name="Patient_RoomTransferHistory" Member="RoomTransferHistories" ThisKey="id" OtherKey="patientID" Type="RoomTransferHistory" />
    </Type>
  </Table>
  <Table Name="dbo.Room" Member="Rooms">
    <Type Name="Room">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="roomName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="bedCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="departmentID" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Association Name="Room_SupplyHistory" Member="SupplyHistories" ThisKey="id" OtherKey="roomID" Type="SupplyHistory" />
      <Association Name="Room_DailyCare" Member="DailyCares" ThisKey="id" OtherKey="roomID" Type="DailyCare" />
      <Association Name="Room_RoomTransferHistory" Member="RoomTransferHistories" ThisKey="id" OtherKey="fromRoomID" Type="RoomTransferHistory" />
      <Association Name="Room_RoomTransferHistory1" Member="RoomTransferHistories1" ThisKey="id" OtherKey="toRoomID" Type="RoomTransferHistory" />
    </Type>
  </Table>
  <Table Name="dbo.RoomTransferHistory" Member="RoomTransferHistories">
    <Type Name="RoomTransferHistory">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="patientID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="fromRoomID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="toRoomID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="transferDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Room_RoomTransferHistory" Member="Room" ThisKey="fromRoomID" OtherKey="id" Type="Room" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="Patient_RoomTransferHistory" Member="Patient" ThisKey="patientID" OtherKey="id" Type="Patient" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Room_RoomTransferHistory1" Member="Room1" ThisKey="toRoomID" OtherKey="id" Type="Room" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Salary" Member="Salaries">
    <Type Name="Salary">
      <Column Name="id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BasicSalary" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Association Name="Salary_SalaryDetail" Member="SalaryDetails" ThisKey="id" OtherKey="SalaryID" Type="SalaryDetail" />
    </Type>
  </Table>
  <Table Name="dbo.SalaryDetail" Member="SalaryDetails">
    <Type Name="SalaryDetail">
      <Column Name="SalaryID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="StaffId" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="SalaryPeriod" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="SalaryDate" Type="System.DateTime" DbType="Date NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="BasicSalary" Type="System.Decimal" DbType="Decimal(18,2) NOT NULL" CanBeNull="false" />
      <Column Name="WorkingDays" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="OvertimeHours" Type="System.Decimal" DbType="Decimal(5,2)" CanBeNull="true" />
      <Column Name="Allowance" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Bonus" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="Deduction" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="IncomeTax" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="SocialInsurance" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="NetSalary" Type="System.Decimal" DbType="Decimal(23,2)" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="Note" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="CreatedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Association Name="Salary_SalaryDetail" Member="Salary" ThisKey="SalaryID" OtherKey="id" Type="Salary" IsForeignKey="true" />
      <Association Name="Staff_SalaryDetail" Member="Staff" ThisKey="StaffId" OtherKey="id" Type="Staff" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Staff" Member="Staffs">
    <Type Name="Staff">
      <Column Name="id" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="name" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="role" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="dob" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="phoneNumber" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="homeAddress" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="citizenID" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="departmentID" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="position" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="qualification" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="degree" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="startDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Staff_Account" Member="Accounts" ThisKey="id" OtherKey="staffID" Type="Account" />
      <Association Name="Staff_SupplyHistory" Member="SupplyHistories" ThisKey="id" OtherKey="nurseID" Type="SupplyHistory" />
      <Association Name="Staff_Appointment" Member="Appointments" ThisKey="id" OtherKey="doctorID" Type="Appointment" />
      <Association Name="Staff_DailyCare" Member="DailyCares" ThisKey="id" OtherKey="nurseID" Type="DailyCare" />
      <Association Name="Staff_DoctorPatient" Member="DoctorPatients" ThisKey="id" OtherKey="doctorID" Type="DoctorPatient" />
      <Association Name="Staff_MedicalOrder" Member="MedicalOrders" ThisKey="id" OtherKey="DoctorID" Type="MedicalOrder" />
      <Association Name="Staff_MedicalRecord" Member="MedicalRecords" ThisKey="id" OtherKey="doctorID" Type="MedicalRecord" />
      <Association Name="Staff_SalaryDetail" Member="SalaryDetails" ThisKey="id" OtherKey="StaffId" Type="SalaryDetail" />
      <Association Name="Department_Staff" Member="Department" ThisKey="departmentID" OtherKey="id" Type="Department" IsForeignKey="true" />
    </Type>
  </Table>
  <Function Name="dbo.sp_GetDailyCaresByPatient" Method="sp_GetDailyCaresByPatient">
    <Parameter Name="PatientId" Parameter="patientId" Type="System.String" DbType="Char(10)" />
    <ElementType Name="sp_GetDailyCaresByPatientResult">
      <Column Name="[Mã chăm sóc]" Member="Mã_chăm_sóc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Tên bệnh nhân]" Member="Tên_bệnh_nhân" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="[Y tá chăm sóc]" Member="Y_tá_chăm_sóc" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Phòng" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Khoa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Ca trực]" Member="Ca_trực" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[Huyết áp]" Member="Huyết_áp" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="[Nhiệt độ (°C)]" Member="Nhiệt_độ___C_" Type="System.Decimal" DbType="Decimal(4,1)" CanBeNull="true" />
      <Column Name="[Nhịp tim (lần/phút)]" Member="Nhịp_tim__lần_phút_" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Ngày chăm sóc]" Member="Ngày_chăm_sóc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="[Ghi chú]" Member="Ghi_chú" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetSupplyHistoryInSameDepartmentFromDate" Method="sp_GetSupplyHistoryInSameDepartmentFromDate">
    <Parameter Name="DoctorId" Parameter="doctorId" Type="System.String" DbType="Char(10)" />
    <Parameter Name="FromDate" Parameter="fromDate" Type="System.DateTime" DbType="Date" />
    <ElementType Name="sp_GetSupplyHistoryInSameDepartmentFromDateResult">
      <Column Name="[Mã cấp thuốc]" Member="Mã_cấp_thuốc" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="[Tên vật tư/thuốc]" Member="Tên_vật_tư_thuốc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Phòng" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Khoa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Tên y tá]" Member="Tên_y_tá" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Tên bệnh nhân]" Member="Tên_bệnh_nhân" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Ngày cấp]" Member="Ngày_cấp" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="[Liều lượng]" Member="Liều_lượng" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Số lượng]" Member="Số_lượng" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Đơn vị]" Member="Đơn_vị" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Ghi chú]" Member="Ghi_chú" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetDailyCaresInSameDepartmentAsDoctorAndDate" Method="sp_GetDailyCaresInSameDepartmentAsDoctorAndDate">
    <Parameter Name="DoctorId" Parameter="doctorId" Type="System.String" DbType="Char(10)" />
    <Parameter Name="TargetDate" Parameter="targetDate" Type="System.DateTime" DbType="Date" />
    <ElementType Name="sp_GetDailyCaresInSameDepartmentAsDoctorAndDateResult">
      <Column Name="[Mã chăm sóc]" Member="Mã_chăm_sóc" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="[Tên bệnh nhân]" Member="Tên_bệnh_nhân" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="[Y tá chăm sóc]" Member="Y_tá_chăm_sóc" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Phòng" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Khoa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Ca trực]" Member="Ca_trực" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[Huyết áp]" Member="Huyết_áp" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="[Nhiệt độ (°C)]" Member="Nhiệt_độ___C_" Type="System.Decimal" DbType="Decimal(4,1)" CanBeNull="true" />
      <Column Name="[Nhịp tim (lần/phút)]" Member="Nhịp_tim__lần_phút_" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Ngày chăm sóc]" Member="Ngày_chăm_sóc" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="[Ghi chú]" Member="Ghi_chú" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetDoctorListByDepartment" Method="sp_GetDoctorListByDepartment">
    <Parameter Name="DepartmentID" Parameter="departmentID" Type="System.String" DbType="Char(10)" />
    <ElementType Name="sp_GetDoctorListByDepartmentResult">
      <Column Name="DoctorID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="DoctorName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="phoneNumber" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="homeAddress" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="citizenID" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="position" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="qualification" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="degree" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="startDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DepartmentName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetMedicalOrdersOfPatientInDoctorDepartment" Method="sp_GetMedicalOrdersOfPatientInDoctorDepartment">
    <Parameter Name="DoctorId" Parameter="doctorId" Type="System.String" DbType="Char(10)" />
    <Parameter Name="PatientId" Parameter="patientId" Type="System.String" DbType="Char(10)" />
    <ElementType Name="sp_GetMedicalOrdersOfPatientInDoctorDepartmentResult">
      <Column Name="[Mã y lệnh]" Member="Mã_y_lệnh" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="[Tên bệnh nhân]" Member="Tên_bệnh_nhân" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[Tên khoa]" Member="Tên_khoa" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[Loại y lệnh]" Member="Loại_y_lệnh" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="[Liều lượng]" Member="Liều_lượng" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Số lượng]" Member="Số_lượng" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Đơn vị]" Member="Đơn_vị" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Tần suất]" Member="Tần_suất" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Ngày bắt đầu]" Member="Ngày_bắt_đầu" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Ngày kết thúc]" Member="Ngày_kết_thúc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="[Trạng thái]" Member="Trạng_thái" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Ghi chú]" Member="Ghi_chú" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="[Ngày ký]" Member="Ngày_ký" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetPatientListByDepartment" Method="sp_GetPatientListByDepartment">
    <Parameter Name="DepartmentID" Parameter="departmentID" Type="System.String" DbType="Char(10)" />
    <ElementType Name="sp_GetPatientListByDepartmentResult">
      <Column Name="PatientID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="fullName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="dob" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="phoneNumber" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="TypePatient" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="citizenID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="InsuranceID" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EmergencyContact" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EmergencyPhone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="createdDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="weight" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="height" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="DepartmentName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetPatientSupplyHistoryInSameDepartment" Method="sp_GetPatientSupplyHistoryInSameDepartment">
    <Parameter Name="DoctorId" Parameter="doctorId" Type="System.String" DbType="Char(10)" />
    <Parameter Name="PatientId" Parameter="patientId" Type="System.String" DbType="Char(10)" />
    <ElementType Name="sp_GetPatientSupplyHistoryInSameDepartmentResult">
      <Column Name="[Mã cấp thuốc]" Member="Mã_cấp_thuốc" Type="System.String" DbType="Char(10)" CanBeNull="true" />
      <Column Name="[Tên vật tư/thuốc]" Member="Tên_vật_tư_thuốc" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Phòng" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Khoa" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Tên y tá]" Member="Tên_y_tá" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Tên bệnh nhân]" Member="Tên_bệnh_nhân" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Ngày cấp]" Member="Ngày_cấp" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="[Liều lượng]" Member="Liều_lượng" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="[Số lượng]" Member="Số_lượng" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[Đơn vị]" Member="Đơn_vị" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Ghi chú]" Member="Ghi_chú" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetPrescriptionReport" Method="sp_GetPrescriptionReport">
    <Parameter Name="PatientID" Parameter="patientID" Type="System.String" DbType="Char(10)" />
    <Parameter Name="OrderDate" Parameter="orderDate" Type="System.DateTime" DbType="Date" />
    <ElementType Name="sp_GetPrescriptionReportResult">
      <Column Name="PrescriptionID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="PatientName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="PatientGender" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="PatientDOB" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="PatientPhone" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="PatientAddress" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PatientInsurance" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="DoctorName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="DoctorPosition" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DoctorQualification" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="DoctorDegree" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="DepartmentName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="OrderDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="DoctorSignedAt" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="MedicineName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Dosage" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Quantity" Type="System.Decimal" DbType="Decimal(8,2)" CanBeNull="true" />
      <Column Name="Unit" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="Frequency" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="Note" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetStaffListByDepartment" Method="sp_GetStaffListByDepartment">
    <Parameter Name="DepartmentID" Parameter="departmentID" Type="System.String" DbType="Char(10)" />
    <ElementType Name="sp_GetStaffListByDepartmentResult">
      <Column Name="StaffID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="StaffName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="StaffRole" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DateOfBirth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="gender" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="phoneNumber" Type="System.String" DbType="VarChar(15)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="homeAddress" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="citizenID" Type="System.String" DbType="VarChar(12)" CanBeNull="true" />
      <Column Name="position" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="qualification" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="degree" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="status" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="startDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="DepartmentName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetSupplyHistoryByDate" Method="sp_GetSupplyHistoryByDate">
    <Parameter Name="dateSupply" Type="System.DateTime" DbType="Date" />
    <ElementType Name="sp_GetSupplyHistoryByDateResult">
      <Column Name="id" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="dateSupply" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="typeSupply" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="dosage" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="unit" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="patientName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="nurseName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="roomName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="departmentName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetSupplyHistoryByPatient" Method="sp_GetSupplyHistoryByPatient">
    <Parameter Name="patientId" Type="System.String" DbType="Char(10)" />
    <ElementType Name="sp_GetSupplyHistoryByPatientResult">
      <Column Name="id" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="dateSupply" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="typeSupply" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="dosage" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="quantity" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="unit" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="note" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="patientName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="nurseName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="roomName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="departmentName" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ItemName" Type="System.String" DbType="NVarChar(255) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
</Database>